wandb_version: 1

epochs:
  desc: null
  value: 2
dataset:
  desc: null
  value: VinDr 5000train 600val
model:
  desc: null
  value: YOLOv8n
image_size:
  desc: null
  value: 1024
batch_size:
  desc: null
  value: 16
machine:
  desc: null
  value: Thermaltake_2080ti_0
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715523339.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.12.3
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
