_wandb:
    value:
        cli_version: 0.17.8
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.17.8
            "8":
                - 5
            "12": 0.17.8
            "13": linux-x86_64
batch_size:
    value: 16
dataset:
    value: FULL_brightnessEQ_VinDr_FIXED_FIXEDBB
epochs:
    value: 50
image_size:
    value: 1024
machine:
    value: Thermaltake_2080ti_0
model:
    value: YOLOv8m
